### ISSUE TITLE
ConfigParser.MissingSectionHeaderError: File contains no section headers.

### ISSUE THREAD

**Issue by MazenElzanaty** [fnzv/nShield#1]
python nshield-main.py 
Traceback (most recent call last):
  File "nshield-main.py", line 12, in <module>
    config.read("/etc/nshield/nshield.conf")
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /etc/nshield/nshield.conf, line: 5
'dryrun = 0\n'

**Comment by MazenElzanaty** [comment]
Fixed by editing the .conf file /etc/nshield/nshield.conf
Added [conf] before dryrun

[conf]
#Enable or Disable Dry-Run to avoid updating current iptables rules
dryrun = 0

# Enable or Disable basic Anti-DDOS
basic_ddos = 1

#Enable aggressive rate-limiting to incoming connections
under_attack = 0

# nShield proxy if enabled checks domain list and creates the nginx conf (Works only for HTTP requests.. SSL still not implemented)
nshield_proxy = 0

**Comment by fnzv** [comment]
Thank you for this issue, the example config file /etc/nshield/nshield.conf on github was using an old format.. i committed the fix to master

**Comment by MazenElzanaty** [comment]
Thank you
